server:
  port: 8187
spring:
  redis:
    host: 47.114.128.1
    port: 6379
    password: 123456
    database: 15
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lowerCaseServiceId: true
      routes:
        - id: testApp1
          uri: lb://testApp1
          predicates:
            - Path=/testA/**
        - id: testApp2
          uri: lb://testApp2
          predicates:
            - Path=/testB/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找


