server:
  port: 8080
spring:
  redis:
    host: 47.114.128.1
    port: 6379
    password: 123456
    database: 15
      #哨兵集群的配置
      #sentinel:
      #  master: mymaster
      #哨兵节点
      #  nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
      #  password: 123456
      #spring.redis.sentinel.  如果有密码则设置密码
      # 连接池最大连接数(使用负值表示没有限制) 默认为8
      #spring.redis.lettuce.pool.max-active=8
      # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
      #spring.redis.lettuce.pool.max-wait=-1ms
      # 连接池中的最大空闲连接 默认为8
      #spring.redis.lettuce.pool.max-idle=8
      # 连接池中的最小空闲连接 默认为 0
    #spring.redis.lettuce.pool.min-idle=0

  rabbitmq:
     host: amqp-cn-7pp2q9yd700l.cn-hangzhou.amqp-2.net.mq.amqp.aliyuncs.com
     port: 5672
     username: MjphbXFwLWNuLTdwcDJxOXlkNzAwbDpMVEFJNXRLN3REQ3h6bXZYYm1Zd1h3WHM=
     password: RjU4MTY3NEUyM0FDMUIyRjE2MTgzOEUwMUNGOUU3RkU1MzI3OTNBRToxNjU0NjE4MTA1ODI0

  application:
    name: application-A
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找


