server:
  port: 8083
spring:
  redis:
    host: 47.114.128.1
    port: 6379
    password: 123456
    database: 15
      #哨兵集群的配置
      #sentinel:
      #  master: mymaster
      #哨兵节点
      #  nodes: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
      #  password: 123456
      #spring.redis.sentinel.  如果有密码则设置密码
      # 连接池最大连接数(使用负值表示没有限制) 默认为8
      #spring.redis.lettuce.pool.max-active=8
      # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
      #spring.redis.lettuce.pool.max-wait=-1ms
      # 连接池中的最大空闲连接 默认为8
      #spring.redis.lettuce.pool.max-idle=8
      # 连接池中的最小空闲连接 默认为 0
    #spring.redis.lettuce.pool.min-idle=0

  rabbitmq:
     host: amqp-cn-7pp2q9yd700l.cn-hangzhou.amqp-2.net.mq.amqp.aliyuncs.com
     port: 5672
     username: MjphbXFwLWNuLTdwcDJxOXlkNzAwbDpMVEFJNXRLN3REQ3h6bXZYYm1Zd1h3WHM=
     password: RjU4MTY3NEUyM0FDMUIyRjE2MTgzOEUwMUNGOUU3RkU1MzI3OTNBRToxNjU0NjE4MTA1ODI0

  application:
    name: application-A

  datasource:
    username: gzr
    password: gzr@1234
    url: jdbc:mysql://rm-bp1gal3hwq8c0e1s51o.mysql.rds.aliyuncs.com:3306/ali_gzr_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource            # 数据库连接池类别
    druid:
      initial-size: 1                                       # 初始化大小
      min-idle: 1                                          # 最小连接数
      max-active: 2                                        # 最大连接数
      max-wait: 20000                                       # 获取连接时的最大等待时间
      min-evictable-idle-time-millis: 300000                # 一个连接在池中最小生存的时间，单位是毫秒
      time-between-eviction-runs-millis: 60000              # 多久才进行一次检测需要关闭的空闲连接，单位是毫秒
      filters: stat,wall                                    # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
      validation-query: SELECT 1                            # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
      test-on-borrow: true                                  # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
      test-on-return: true                                  # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
      test-while-idle: true                                 # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能
      stat-view-servlet:
        enabled: true                                       # 是否开启 StatViewServlet
        allow: 127.0.0.1                                    # 访问监控页面 白名单，默认127.0.0.1
        deny: 192.168.56.1                                  # 访问监控页面 黑名单
        login-username: admin                               # 访问监控页面 登陆账号
        login-password: admin                               # 访问监控页面 登陆密码
      filter:
        stat:
          enabled: true                                     # 是否开启 FilterStat，默认true
          log-slow-sql: true                                # 是否开启 慢SQL 记录，默认false
          slow-sql-millis: 30000                             # 慢 SQL 的标准，默认 3000，单位：毫秒
          merge-sql: false                                  # 合并多个连接池的监控数据，默认false

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.test.appA.entity
# 输出sql语句日志
logging:
  level:
    com:
      springboot:
        dao: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找


